### ISSUE TITLE
인자로 47이상을 주면 음수값이 나왔다 말았다 합니다.

### ISSUE THREAD

**Issue by ycha** [GDGKoreaWomen/gdg_codelab_1404#2]
지나가던 어떤 푸로구라머께서 실행하는 방법을 알려주셔서, 이렇게 저렇게 실행해봤는데요.

실행할 때 값을 47보다 크게 주면 출력물에서 음수가 나옵니다.

![image](https://f.cloud.github.com/assets/221114/2367656/8a3b52fe-a770-11e3-8c38-dff646e91391.png)

뭔가 이상한데요. 해결해주세요.

**Comment by sebang** [comment]
47th 피보나치 수 : 2971215073
데이터 형이 INT일 경우, INT 범위를 넘어가서 연산 값이 정상적으로 나오지 않는 것 같습니다.

**Comment by Nerrtica** [comment]
unsigned int 나 long 형을 사용하면 좀 더 큰 값까지 결과를 얻을 수 있을 것 같네요~

**Comment by Bloodevil** [comment]
#8 에 pull request 보냈습니다.

**Comment by jjuakim** [comment]
이 버그에대해서는 수정된것 같아 보이니 이슈를 닫겠습니다
